server:
  servlet:
    context-path: /short-url-jpa-service
  port: 10004

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: short-url-jpa-service
  datasource:
    url: jdbc:postgresql://192.168.0.206:26257/url_shortner
    username: root
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false

---

server:
  servlet:
    context-path: /short-url-jpa-service
  port: 10004

spring:
  config:
    activate:
      on-profile: dev
  threads:
    virtual:
      enabled: true
  application:
    name: short-url-jpa-service
  datasource:
    url: jdbc:postgresql://192.168.0.206:26257/url_shortner
    username: root
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false
