server:
  port: 10003

spring:
  datasource:
    url: jdbc:postgresql://192.168.0.206:26257/url_shortner
    username: root
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true

duid:
  server: http://localhost:10001/
